baseURL = "https://keyin.me/"
languageCode = "zh-cn"
title = "World of Forks"



# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true

# DO　NOT MODIFY THIS CONFIG/不要修改这个配置
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Kevin Tan"
  subtitle = "Tempora mutantur, nos et mutamur in illis ..."
  copyright = "Copyleft@Kevin Tan"
  logo = "/img/avatar.jpg"
  profile_background = "/img/20.jpg"
  nest_bg = false
  load_animation = true
  
# 评论
[params.comment]
  type = "disqus"

[params.comment.valine]
  id = "drenIDLMO3yTwiuCl7Hva9nq-gzGzoHsz"
  key = "rfotKaw6cevwHhOR8FvhwPAp"
  placeholder = "写点什么吧..."
  avatar = "retro"

[params.comment.disqus]
  shortname = 'keyin'


# 主菜单
[[menu.main]]
    name = "Home"
    weight = 1
    pre = "<i class='material-icons'>home</i>"
    url = "/"

[[menu.main]]
    name = "Archive"
    weight = 2
    pre = "<i class='material-icons'>archive</i>"
    url = "/archive/"

# [[menu.main]]
#     name = "Category"
#     weight = 3
#     pre = "<i class='material-icons'>class</i>"
#     url = "/categories/"

# [[menu.main]]
#     name = "Tag"
#     weight = 4
#     pre = "<i class='material-icons'>local_offer</i>"
#     url = "/tags/"

[[menu.main]]
    name = "About"
    weight = 6
    pre = "<i class='material-icons'>person</i>"
    url = "/about/"

#  友情链接
[[menu.friend]]
  name = "Frantic1048"
  url = "https://frantic1048.logdown.com/"

[[menu.friend]]
  name = "HclMaster"
  url = "https://hclmaster.github.io/"

[[menu.friend]]
  name = "WANG Hsü-Tung"
  url = "https://whst.github.io/"


# 社交账号
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  url = "https://github.com/stkevintan"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-twitter'><use xlink:href='#svg-icons-twitter'></use></svg>"
  name = "Twitter"
  url = "https://twitter.com/kevinsfork"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-sina-weibo'><use xlink:href='#svg-icons-sina-weibo'></use></svg>"
  name = "Weibo"
  url = "http://weibo.com/kevinclasky"


# # 文章归类类目
# [[menu.taxonomy]]
#   pre = "<i class='material-icons'>local_offer</i>"
#   name = "Tag"
#   identifier="tags"

# [[menu.taxonomy]]
#   pre = "<i class='material-icons'>class</i>"
#   name = "Category"
#   identifier="categories"

